import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import TabProvider from "@/context/TabContext";
import { ThemeProvider } from "@/components/Themeprovider";
import FloatingActionMenu from "@/components/ui/floating-action-menu";
import MagicNavigation from "@/components/MobileNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Pop = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Pop.className} antialiased`}
      >
        <ThemeProvider
          defaultTheme="system"
          storageKey="vite-ui-theme"
          attribute="class"
          enableSystem
          disableTransitionOnChange
        >
          <TabProvider>
            {children}
            <Sidebar />
            <MagicNavigation />
            <FloatingActionMenu className="fixed top-4 right-4 md:right-10" />
          </TabProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
